[tool.poetry]
name = "repl_python3_Stronghold-app"
version = "0.1.0"
description = ""
authors = ["SuperComputer29 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
